---
# Source: mailu/templates/secret-initial-account.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mailu-initial-account
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-0.3.3
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  initial-account-password: "Y2hhbmczbTMh"
