---
# Source: mailu/templates/dovecot/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-dovecot
  namespace: "mailu"
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-0.3.3
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dovecot
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mailu
      app.kubernetes.io/instance: mailu
      app.kubernetes.io/component: dovecot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailu
        helm.sh/chart: mailu-0.3.3
        app.kubernetes.io/instance: mailu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: dovecot
    spec:
      
      terminationGracePeriodSeconds: 2
      containers:
        - name: dovecot
          image: mailu/dovecot:master
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              subPath: dovecotdata
              mountPath: /data
            - name: data
              subPath: dovecotmail
              mountPath: /mail
          env:
            - name: LOG_LEVEL
              value: WARNING
            - name: FRONT_ADDRESS
              value: mailu-front.mailu.svc.cluster.local
            - name: ADMIN_ADDRESS
              value: mailu-admin.mailu.svc.cluster.local
            - name: ANTISPAM_WEBUI_ADDRESS
              value: mailu-rspamd.mailu.svc.cluster.local:11334
            - name: POSTMASTER
              value: postmaster
            - name: DOMAIN
              value: example.com
            - name: HOSTNAMES
              value: "mail.example.com,imap.example.com"
            - name: RECIPIENT_DELIMITER
              value: +
            # TODO: COMPRESSION / COMPRESS_LEVEL -> documentation?
            - name: WEBMAIL
              value: none
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailu-secret
                  key: secret-key
          envFrom:
          ports:
            - name: auth
              containerPort: 2102
              protocol: TCP
            - name: lmtp
              containerPort: 2525
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
            - name: pop3
              containerPort: 110
              protocol: TCP
            - name: sieve
              containerPort: 4190
              protocol: TCP
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - sh
                - -c
                - 'echo QUIT|nc localhost 110|grep "Dovecot ready."'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - sh
                - -c
                - 'echo QUIT|nc localhost 110|grep "Dovecot ready."'
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailu-storage
