---
# Source: mailu/templates/roundcube/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-roundcube
  namespace: "mailu"
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-1.0.0
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: roundcube
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mailu
      app.kubernetes.io/instance: mailu
      app.kubernetes.io/component: roundcube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailu
        helm.sh/chart: mailu-1.0.0
        app.kubernetes.io/instance: mailu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: roundcube
    spec:
      
      terminationGracePeriodSeconds: 2
      containers:
        - name: roundcube
          image: mailu/roundcube:master
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: roundcube
          env:
            - name: LOG_LEVEL
              value: WARNING
            - name: MESSAGE_SIZE_LIMIT
              value: "52428800"
            - name: IMAP_ADDRESS
              value: mailu-dovecot.mailu.svc.cluster.local
            - name: FRONT_ADDRESS
              value: mailu-front.mailu.svc.cluster.local
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mailu-secret
                  key: secret-key
            - name: SUBNET
              value: 10.42.0.0/16
            - name: ADMIN
              value: "true"
            - name: WEB_ADMIN
              value: "/admin/"
            - name: ROUNDCUBE_DB_FLAVOR
              value: sqlite
          envFrom:
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command: [ "curl", "-f", "-L", "-H", "User-Agent: health", "http://localhost/" ]
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command: [ "curl", "-f", "-L", "-H", "User-Agent: health", "http://localhost/" ]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailu-storage
