---
# Source: mailu/templates/admin/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mailu-admin
  namespace: "mailu"
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-1.0.0
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admin
spec:
  selector:
    app.kubernetes.io/name: mailu
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/component: admin
  ports:
  - name: http
    port: 80
    protocol: TCP
