---
# Source: mailu/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mailu-storage
  namespace: "mailu"
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-1.0.0
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  resources:
    requests:
      storage: "100Gi"
  storageClassName: default
