---
# Source: mailu/templates/postfix/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-postfix
  namespace: "mailu"
  labels:
    app.kubernetes.io/name: mailu
    helm.sh/chart: mailu-1.0.0
    app.kubernetes.io/instance: mailu
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postfix
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mailu
      app.kubernetes.io/instance: mailu
      app.kubernetes.io/component: postfix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailu
        helm.sh/chart: mailu-1.0.0
        app.kubernetes.io/instance: mailu
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: postfix
    spec:
      
      terminationGracePeriodSeconds: 2
      containers:
        - name: postfix
          image: mailu/postfix:master
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /queue
              name: data
              subPath: mailqueue
          env:
            - name: LOG_LEVEL
              value: WARNING
            - name: REJECT_UNLISTED_RECIPIENT
              value: "yes"
            - name: DOMAIN
              value: "example.com"
            - name: HOSTNAMES
              value: "mail.example.com,imap.example.com"
            - name: MESSAGE_SIZE_LIMIT
              value: "52428800"
            - name: SUBNET
              value: "10.42.0.0/16"
            - name: RECIPIENT_DELIMITER
              value: "+"
            - name: LMTP_ADDRESS
              value: mailu-dovecot.mailu.svc.cluster.local:2525
            - name: ANTISPAM_MILTER_ADDRESS
              value: mailu-rspamd.mailu.svc.cluster.local:11332
            - name: ADMIN_ADDRESS
              value: mailu-admin.mailu.svc.cluster.local
            - name: FRONT_ADDRESS
              value: mailu-front.mailu.svc.cluster.local
            
          envFrom:
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: smtp-ssl
              containerPort: 465
              protocol: TCP
            - name: smtp-starttls
              containerPort: 587
              protocol: TCP
            - name: smtp-auth
              containerPort: 10025
              protocol: TCP
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - sh
                - -c
                - 'echo QUIT|nc localhost 25|grep "220 .* ESMTP Postfix"'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - sh
                - -c
                - 'echo QUIT|nc localhost 25|grep "220 .* ESMTP Postfix"'
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mailu-storage
